FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

ENV ASPNETCORE_URLS=http://+:5000

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ["agileways.usermgt.admin.client/Server/agileways.usermgt.admin.client.Server.csproj", "agileways.usermgt.admin.client/Server/"]
COPY ["agileways.usermgt.shared/agileways.usermgt.shared.csproj", "agileways.usermgt.shared/"]
COPY ["agileways.usermgt.shared.server/agileways.usermgt.shared.server.csproj", "agileways.usermgt.shared.server/"]
COPY ["agileways.usermgt.admin.client/Client/agileways.usermgt.admin.client.Client.csproj", "agileways.usermgt.admin.client/Client/"]

RUN dotnet restore "agileways.usermgt.admin.client/Server/agileways.usermgt.admin.client.Server.csproj"
RUN dotnet restore "agileways.usermgt.shared.server/agileways.usermgt.shared.server.csproj"
RUN dotnet restore "agileways.usermgt.shared/agileways.usermgt.shared.csproj"
RUN dotnet restore "agileways.usermgt.admin.client/Client/agileways.usermgt.admin.client.Client.csproj"

COPY . .

WORKDIR "/src/agileways.usermgt.admin.client/Server"

RUN dotnet build "agileways.usermgt.admin.client.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "agileways.usermgt.admin.client.Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "agileways.usermgt.admin.client.Server.dll"]
