# This is a basic workflow to help you get started with Actions

name: common-endpoint-rp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
    - 'policies/SocialAndLocalAccounts/**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 'Replace tokens in Common Endpoint and TOU policy files'
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["./policies/SocialAndLocalAccounts/CommonEndpoint/*.xml", "./policies/SocialAndLocalAccounts/TermsOfUse/*.xml"]'
        env:
          Settings:Tenant: ${{ secrets.TENANT_ID }}
          Settings:AppInsightsKey: ${{ secrets.APPINSIGHTSKEY }}
          Settings:DeploymentMode: ${{ secrets.DEPLOYMENTMODE }}
          Settings:CurrentTermsOfUseVersion: ${{ secrets.CURRENTTERMSOFUSEVERSION }}
          

      - name: 'Upload TrustFrameworkBase Policy for Common Endpoint'
        uses: azure-ad-b2c/deploy-trustframework-policy@v5.3
        with:
          folder: "./policies/SocialAndLocalAccounts/CommonEndpoint"
          files: "01-BuildingBlocks.xml,05-ClaimsProviders.xml,10-UserJourneys.xml,RP-SIgnUpSignIn.xml"
          tenant: ${{ secrets.TENANT_ID }}
          clientId: ${{ secrets.SPN_CLIENTID }}
          clientSecret: ${{ secrets.SPN_CLIENTPWD }}
          verbose: false

      - name: 'Upload TrustFrameworkBase Policy for Terms of Use'
        uses: azure-ad-b2c/deploy-trustframework-policy@v5.3
        with:
          folder: "./policies/SocialAndLocalAccounts/TermsOfUse"
          files: "01-BuildingBlocks.xml,05-ClaimsProviders.xml,10-UserJourneys.xml,RP-SUSI.xml"
          tenant: ${{ secrets.TENANT_ID }}
          clientId: ${{ secrets.SPN_CLIENTID }}
          clientSecret: ${{ secrets.SPN_CLIENTPWD }}
          verbose: false
